TugasPPW1/urls.py
from django.conf.urls import url,include
from django.contrib import admin

import update_status.urls as update_status 
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile

import dashboard.urls as dashboard

from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(permanent = True, url = 'update-status/')),
    url(r'^profile/', include(halaman_profile, namespace= "halaman-profile")),
	url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^statistic/', include(dashboard, namespace='dashboard')),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_new_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-new-friend', add_new_friend, name='add-new-friend'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_todo

urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
]

urls.py
from django.conf.urls import url
from .views import index, add_todo

import dashboard.urls as dashboard


urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
	url(r'^statistic/', include(dashboard, namespace = 'dashboard')),
]

add_friend/models.py
from django.db import models

# Create your models here.

class Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

dashboard/models.py
from django.db import models

# Create your models here.

halaman_profile/models.py
from django.db import models

class halamanProfile(models.Model):
	name = models.CharField(max_length = 150)
	birthday = models.DateField(default = '1998-10-04')
	gender = models.CharField(max_length = 6)
	expertise = models.CharField(max_length = 250)
	description = models.CharField(max_length = 250)
	email = models.CharField(max_length = 150)

update_status/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
	title = models.CharField(max_length=27)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=True, max_length=27, widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(label='url', required=True,widget=forms.TextInput(attrs=attrs))

update_status/forms.py
from django import forms

class Todo_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
	}
	#title_attrs = {
	#	'type': 'text',
	#	'class': 'todo-form-input',
	#	'placeholder':'Masukan judul...'
	#}
	
	description_attrs = {
		'type': 'text',
		'cols': 50,
		'rows': 4,
		'class': 'todo-form-textarea',
		'placeholder':'Apa yang anda pikirkan? '
	}

	#title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
	description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

add_friend/views.py
from django.shortcuts import render, redirect
from .forms import Add_Friend_Form
from .models import Friend
from django.http import HttpResponseRedirect

response = {}

def index(request):
    html = 'add_friend.html'
    response['message_form'] = Add_Friend_Form
    response['friend'] = Friend.objects.all()
    return render(request, html, response)

def add_new_friend(request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friend(name=response['name'],url=response['url'])
        friend.save()
        return HttpResponseRedirect('/add-friend/')
    else:
        return HttpResponseRedirect('/add-friend/')

dashboard/views.py
from django.shortcuts import render

from update_status.models import Todo #nyari status pertama dan jumlah feeds
from halaman_profile.models import halamanProfile #nyari foto
from add_friend.models import Friend #nyari jumlah teman
from halaman_profile.views import profile

from add_friend.forms import Add_Friend_Form #nyari temen

response = {}
def index(request):
	response['jumlahteman'] = Friend.objects.all().count()
	response['profile'] = profile
	response['statusterakhir'] = Todo.objects.all().last()
	response['jumlahstatus'] = Todo.objects.all().count()
	return render(request, 'dashboard.html', response)

halaman_profile/views.py
from django.shortcuts import render
from .models import halamanProfile

profile = halamanProfile(name = "Narahama Lalala", birthday = "1998-10-04", gender = "Female", expertise = "Coding, Writing, Singing", description = "A college student in her second year", email = "narahama@ui.ac.id")
response = {"name": profile.name, "birthday": profile.birthday, "gender": profile.gender, "expertise": profile.expertise, "description": profile.description, "email": profile.email}

def index(request):
	return render(request, 'halaman_profile.html', response)


# Create your views here.

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Narahama Lalala" #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    html = 'lab_5/lab_5.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        #response['title'] = request.POST['title']
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

add_friend/templates/add_friend.html
{% extends "base.html" %}
{% block content %}
<style>
        .subject{
            font-size: 20px;
            font-family: "Comic Sans MS";
            color: #6650ff;
        }
        .value{
            font-size: 20px;
            font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
            color: #D9094E;
        }
    
    tr:nth-child(even){background-color: #f2f2f2}


</style>

<div class="container">
<center><h1 > Add Friend</h1></center>

<section name="form", id="input-list">
    <form id="form" method="POST" action="/add-friend/add-new-friend">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>
<hr/>

<table class="table">
    <thead>
        <th>Nama</th>
        <th>URL</th>
        <th>Created Date</th>
    </thead>
    <tbody>
        {% for i in friend %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning"> {% else %} <tr class="success">
            {% endif %}
            <td> {{i.name}} </td>
            <td> <a href = "{{i.url}}"> {{i.url}} </a></td>
            <td> {{i.created_date}}</td>
        </tr>             
        {% endfor %}
    </tbody>
</table>
{% endblock %}
</div>

dashboard/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<h1>Statistic</h1>

<div class = "stats">
<section class = "profile">
	<p class = "name"><img src = "https://image.ibb.co/b6xHGG/nopic1.png" class = "rounded-image" alt = "narahama jepege">  {{profile.name}}</p>
</section>

<section class = "friendsdanfeed">
	<P>Friends {{jumlahteman}} Post {{jumlahstatus}}</p>
</section>

<section class = "latestpost" id = "labelpost">
	<p class = "latepostlabel">Latest Post</p>
	<p class = "namakecil"> <img src = "https://image.ibb.co/b6xHGG/nopic1.png" class = "rounded-image-kecil" alt = "narahama jepege"> {{profile.name}}</p> 
	<p class = "descriptionstyle">{{statusterakhir.description}}</p> 
	<p class = "created_datestyle">Posted on {{statusterakhir.created_date}}</p>
</section>
</div>

<style>
	.stats {
		border : none;
		text-align : center;
	}
	.profile {
		font-weight : bold;
	}
	.rounded-image{
        border-radius: 100%;
        width: 180px;
        height: 180px;
    }
	.name {
		font-size : 22px;
		text-align : center;
	}
	.descriptionstyle {
		font-family : sans-serif;
		font-size : 14px;
		font-weight : bold;
	}
	.created_datestyle {
		font-size : 10px;
		font-style :oblique;
	}
	.rounded-image-kecil {
		border-radius : 100%;
		width: 40px;
		height: 40px;
	}
	.namakecil {
		font-size : 16px;
	}
	.latepostlabel {
		font-style : sans-serif;
		font-size : 18px;
	}
	#labelpost {
		border-radius: 25px;
		border: 2px solid #73AD21;
		padding: 20px; 
		background-color : white;
		width: 400px;
		height: 200px;
	}
	.latestpost {
		margin : auto;
		padding : 10px;
	}
</style>
{% endblock %}

halaman_profile/templates/halaman_profile.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'narahama_style.css' %}" />
<style>
    table, th, td {
    border: none;
    outline: none;
    width: 450px;
    font-size: 14px;
    font: "Verdana"
}
.subject{
    font-size: 14px;
    font-family: "Verdana";
    color: #000000;
}
.value{
    font-size: 14px;
    font-family: "Verdana";
    color: #000000;
}
.center_top {
    margin: auto;
    text-align: center
}
.center_screen {
    margin: auto;
    width: 400px;
}
.round{
    border-radius: 100%;
    width: 180px;
    height: 180px;
    margin: auto;
    background-image: url('https://image.ibb.co/b6xHGG/nopic1.png');
}
</style>
<h5 style="text-align: left; padding: 20px">Profile</h5>
<div class="round">
    <img align="center">
</div>
<br>
<div class="center_top">
    <a><b>{{ name }}</b></a>
</div>
<br>
<div class="center_screen">
    <table>
            <tr>
                <td>Birthday</td>
                <td>{{birthday}}</td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>{{gender}}</td>
            </tr>
            <tr>
                <td>Expertise</td>
                <td>{{expertise}}</td>
            </tr>
             <tr>
                <td>Description</td>
                <td>{{description}}</td>
            </tr>
             <tr>
                <td>Email</td>
                <td>{{email}}</td>
            </tr>
    </table>
</div>
<br><br>
{% endblock %}

halaman_profile/templates/partials/footer.html
<p>&copy; Made with love by Narahama</p>

<!-- cara pakenya diinclude gitu di tag <footer> -->

halaman_profile/templates/partials/navbar.html
<!DOCTYPE HTML>
<head>
    <meta charset="UTF-8">
    <title>Ling In</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Ling In</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">Status</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Friends</a>
              </li>
			  <li class="nav-item">
				<a class="nav-link" href="#">Stats</a>
			  </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    
    <style>
  body{background: #3494E6;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #EC6EAD, #3494E6);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #EC6EAD, #3494E6); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}</style>
</head>

    <header>
      {% include "partials/navbar.html" %}
    </header>
    <content>
      {% block content %}
      {% endblock %}
    </content>
    <footer>
      {% block footer %}
      {% include "partials/footer.html" %}
      {% endblock %}
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</body>
</html>

templates/partials/footer.html
<p>&copy; Made with love by Narahama</p>

<!-- cara pakenya diinclude gitu di tag <footer> -->

templates/partials/navbar.html
<!DOCTYPE HTML>
<head>
    <meta charset="UTF-8">
    <title>Ling In</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Ling In</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/update-status/">Status</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/profile/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/add-friend">Friends</a>
              </li>
			  <li class="nav-item">
				<a class="nav-link" href="/statistic/">Stats</a>
			  </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>

update_status/templates/lab_5.html
{% extends "base.html" %}
{% block content %}

<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'lab-5:add_todo' %}">
            <h2>Input Todo</h2>
            {% csrf_token %}
            {{ todo_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">My List</h2>
        <div class="flex">
            {% if todo %}
                {% for data in todo %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-title">
                                {{data.title}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="to-do-list-description">
                                {{data.description}}
                            </div>
                            <div class="to-do-list-delete">
                                <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}   

update_status/templates/lab_5/lab_5.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<!--<h1 class="main-title">NA-RA-HA-MA</h1>-->
<hr/>
<link rel="stylesheet" type="text/css" href="{% static 'css/narahama_style.css' %}" />
<style type="text/css">
    .todo-form-textarea {
        width: 100%;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <section name="input-list" id="input-list">
                <div class="container">
                    <form id="form" method="POST" action="{% url 'update-status:add_todo' %}">
                        <h2>Update Status</h2>
                        <br>
                        {% csrf_token %}
                        {{ todo_form }}

                        <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
                        
                    </form>
                    <br>
                    
                </div>
            </section>
        </div>
        <div class="col-sm-6">
            <section name="my-list" id="my-list" style="padding-bottom: 20px">


            {% if todo %}
                {% for data in todo %}
                    
                    <div class="container">
                        <div class="row">
                        <div class="col-sm-8 col-sm-offset-2">  
                            <div class= "media" style="padding: 40px">
                                <div class= "media-left">
                                    <img src="https://image.ibb.co/b6xHGG/nopic1.png" class="media-object
                                    img-circle" style= "width:75px">
                                </div>
                                <div class="media-body" style="padding-left:10px">

                                    <h4 class="media-heading"><strong>{{author}}</strong> <small><i> Posted on
                                    {{data.created_date}}</i></small></h4>
                                    <p>{{data.description}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                    
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        <!--</div> -->
    
</section>
        </div>
    </div>
</div>



{% endblock %}   